#!/usr/bin/env sh
apk add --no-cache sudo
cat <<EOF > /etc/sudoers
# Generated by Bob the Buildah script (https://github.com/taqtiqa/bob)
#   bob/scripts/${OCI_DISTRIB_ID}/${OCI_DISTRIB_CODENAME}/sudo/install.sh
root ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD: ALL
EOF